name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NODE_ENV: ci
  CI: true
jobs:
  test:
    name: Test Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Run Tests
        run: yarn test
